name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      PYTHONPATH: .

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        cache: 'pip'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r requirements-dev.txt
        pip install -e .

    - name: Run Tests
      run: |
        pytest --cov=tutor_stack_notifier --cov-report=xml

    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v4.0.1
      with:
        file: ./coverage.xml
        flags: notifier
        name: notifier-coverage

  lint:
    runs-on: ubuntu-latest
    env:
      PYTHONPATH: .
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        cache: 'pip'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r requirements-dev.txt

    - name: Run black
      run: black --check tutor_stack_notifier tests

    - name: Run isort
      run: isort --check-only tutor_stack_notifier tests

    - name: Run flake8
      run: flake8 tutor_stack_notifier tests

    - name: Run mypy
      run: mypy tutor_stack_notifier tests

  build:
    runs-on: ubuntu-latest
    needs: [test, lint]
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'

    steps:
    - uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: false
        tags: notifier-service:latest
        cache-from: type=gha
        cache-to: type=gha,mode=max 